### ISSUE TITLE
socket.emit from server.js to client.js doesn't work !

### ISSUE THREAD

**Issue by flashios09** [Wisembly/elephant.io#115]
Hi @Taluu ,
Thanks for this PHP package :+1: 
Sorry for my bad english :(
I'm using the **cakephp framework**, i have a login view **myproject/login**, after a user **is logged** i **emit** an event with ElephantIO and **redirect** it to **myproject/admin** like this:
```php
public function login(){
    if ($this->request->is('post')) {
        $user = $this->Auth->identify();

        if ($user) {
            // User is logged 
            // -> emit an event to Server.js
            ElephantIOTrait::emit('ElephantIO.login', $user);
            // -> redirect the user to 'myproject/admin'
            return $this->redirect('/admin');
        }
    }
}
```
Then with Server.js i want to **re-emit** another **event to only for this connected user** using ```socket.emit``` to **Client.js**:
```js
// Server.js
io.on('connection', function (socket){
    logger.info('SocketIO > Connected socket ' + socket.id);

    socket.on('ElephantIO.login', function (user){
        // The event that i want to re-emit to Client.js
        socket.emit('SocketIO.login', user);
    });


    socket.on('disconnect', function () {
        logger.info('SocketIO > Disconnected socket ' + socket.id);
    });
});
```
```js
// Client.js
(function() {
    var socket = io.connect('http://localhost:1337');

    socket.on('SocketIO.login', function(user) {
        alert('SocketIO.login');
        console.log(user)
    });

})();
```
I don't have any response or an error !
If i change the re-emit event ```socket.emit('SocketIO.login', user);``` with ```socket.broadcast.emit('SocketIO.login', user);```, the **other opened browser window** will have **the alert popup**.
If i change the re-emit event ```socket.emit('SocketIO.login', user);``` with ```io.emit('SocketIO.login', user);```, **only the other opened browser window** will have **the alert popup** like the behavior of  ```socket.broadcast.emit('SocketIO.login', user);```
Always the current window doesn't have a response or an error ! Like the current window socket is ignored !

**Comment by Taluu** [comment]
Hi,

The read part from Elephant.io is flawed and doesn't work currently, even if there are some ideas to make it work, I just didn't have the time to develop those (https://github.com/Wisembly/Elephant.io/issues/74#issuecomment-56103467). As there have been some merges done since then, I need to look at those fixes and see how I could adapt those whenever I'll get enough time to do that.

But to be frank, seeing the problems this read method develops, I'm not quite sure if I should not just remove that (as we don't need it here in Wisembly... we're not even needing Elephant.io anymore :{), and leave it to an external and motivated contributor to do that, i'd be happy to merge ! :}
