### ISSUE TITLE
How to check is connection open? How to increase timeout?

### ISSUE THREAD

**Issue by BashkovAnd** [Wisembly/elephant.io#177]
Hello! I have 2 questions:
1) How to check is connection open? 
2) How to increase timeout from 60 seconds?
I tried 
$client = new Client(new Version2X('http://localhost:1337', [
    'timeout' => 120
]));
but it doesn't help - client disconnected after 60 seconds.
Thank You!

**Comment by Taluu** [comment]
Hi,

It's currently not in the public api to check if the socket is still connected. PRs are welcome. If you need to have such a timeout, are you using elephant to read data rather than just send them ?

If that's the case, the read is not really working ATM, and I would suggest you not to try it. There are multiple bugs on it, and as I stopped using Elephant ages ago, I currently have no plan to do extended maintenance on it... If I were you, I would look for another library, such as Woketo from @Nek- : https://github.com/Nekland/Woketo

To increase the timeout, I think instead of trying to set the option, you should maybe look into your php configuration and increase the socket_timeout config.

**Comment by BashkovAnd** [comment]
Hello!
Thank you for answer!
I will try to figure out with another library...
